# Generated by Django 5.2.7 on 2025-12-05 21:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("game", "0001_initial"),
        ("game", "0002_alter_item_options_battle_loser_and_more"),
        ("game", "0003_remove_battle_challenger_remove_battle_duelist_and_more"),
        ("game", "0004_battle_exp_reward_battle_gold_reward"),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("price", models.PositiveIntegerField()),
                ("level_required", models.PositiveIntegerField(default=1)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("weapon", "Weapon"),
                            ("armor", "Armor"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=63,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sword", "Sword"),
                            ("axe", "Axe"),
                            ("staff", "Staff"),
                            ("magic_sword", "Magic Sword"),
                            ("bow", "Bow"),
                            ("crossbow", "Crossbow"),
                            ("heavy_armor", "Heavy Armor"),
                            ("medium_armor", "Medium Armor"),
                            ("light_armor", "Light Armor"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=63,
                    ),
                ),
                ("bonus_damage", models.PositiveIntegerField(default=0)),
                ("bonus_protection", models.PositiveIntegerField(default=0)),
                ("bonus_health", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
                ("description", models.TextField()),
                ("damage_base", models.PositiveIntegerField()),
                ("protection_base", models.PositiveIntegerField()),
                ("health_base", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("max_characters", models.PositiveIntegerField(default=6)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "player",
                "verbose_name_plural": "players",
                "ordering": ["username"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
                ("level", models.PositiveIntegerField(default=1)),
                ("current_exp", models.PositiveIntegerField(default=0)),
                ("gold", models.PositiveIntegerField(default=0)),
                ("damage", models.PositiveIntegerField(default=1)),
                ("health", models.PositiveIntegerField(default=100)),
                ("protection", models.PositiveIntegerField(default=1)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipped_accessory",
                    models.ForeignKey(
                        limit_choices_to={"slot": "accessory"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters_with_accessory",
                        to="game.item",
                    ),
                ),
                (
                    "equipped_armor",
                    models.ForeignKey(
                        limit_choices_to={"slot": "armor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters_with_armor",
                        to="game.item",
                    ),
                ),
                (
                    "equipped_weapon",
                    models.ForeignKey(
                        limit_choices_to={"slot": "weapon"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="characters_with_weapon",
                        to="game.item",
                    ),
                ),
                (
                    "inventory",
                    models.ManyToManyField(related_name="characters", to="game.item"),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="game.profession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "challenger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_as_challenger",
                        to="game.character",
                    ),
                ),
                (
                    "duelist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_as_duelist",
                        to="game.character",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battles_as_winner",
                        to="game.character",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="allowed_professions",
            field=models.ManyToManyField(
                related_name="allowed_items", to="game.profession"
            ),
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
                ("description", models.TextField()),
                ("damage_modifier", models.FloatField()),
                ("protection_modifier", models.FloatField()),
                ("health_modifier", models.FloatField()),
                (
                    "allowed_professions",
                    models.ManyToManyField(
                        related_name="allowed_races", to="game.profession"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="character",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="game.race",
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["level"], name="game_charac_level_191bca_idx"),
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("slot", "type", "level_required", "name")},
        ),
        migrations.AddField(
            model_name="battle",
            name="loser",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="battles_as_loser",
                to="game.character",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="equipped_accessory",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"slot": "accessory"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters_with_accessory",
                to="game.item",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="equipped_armor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"slot": "armor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters_with_armor",
                to="game.item",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="equipped_weapon",
            field=models.ForeignKey(
                blank=True,
                default=1,
                limit_choices_to={"slot": "weapon"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters_with_weapon",
                to="game.item",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="inventory",
            field=models.ManyToManyField(
                blank=True, related_name="characters", to="game.item"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only 2-12 latin letters.",
                        regex="^[a-zA-Z]{2,12}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("sword", "Sword"),
                    ("mace", "Mace"),
                    ("dagger", "Dagger"),
                    ("axe", "Axe"),
                    ("staff", "Staff"),
                    ("magic_sword", "Magic Sword"),
                    ("bow", "Bow"),
                    ("crossbow", "Crossbow"),
                    ("heavy_armor", "Heavy Armor"),
                    ("medium_armor", "Medium Armor"),
                    ("light_armor", "Light Armor"),
                    ("accessory", "Accessory"),
                ],
                max_length=63,
            ),
        ),
        migrations.RemoveField(
            model_name="battle",
            name="challenger",
        ),
        migrations.RemoveField(
            model_name="battle",
            name="duelist",
        ),
        migrations.AddField(
            model_name="battle",
            name="attacker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="battles_as_attacker",
                to="game.character",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="defender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="battles_as_defender",
                to="game.character",
            ),
        ),
        migrations.AddField(
            model_name="battle",
            name="exp_reward",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="battle",
            name="gold_reward",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
